export * as A from 'fp-ts/Array'
export * as E from 'fp-ts/Either'
export * as Eq from 'fp-ts/Eq'
export * as IO from 'fp-ts/IO'
export * as IOE from 'fp-ts/IOEither'
export * as M from 'fp-ts/Monoid'
export * as O from 'fp-ts/Option'
export * as Ord from 'fp-ts/Ord'
export * as R from 'fp-ts/Record'
export * as T from 'fp-ts/Task'
export * as TE from 'fp-ts/TaskEither'

export * as B from 'fp-ts/boolean'
export * as N from 'fp-ts/number'
export * as NEA from 'fp-ts/NonEmptyArray'
export * as S from 'fp-ts/string'
export * as Sg from 'fp-ts/Semigroup'

export * as D from 'io-ts/Decoder'
