export const GROUP_MEMBER_PREFIX = 'TELEGRAM_GROUP_MEMBERS_'
export const EXHENTAI_DOWNLOADS = 'EXHENTAI_DOWNLOADS'
export const TWITTER_SENT_LIST = 'TWITTER_SENT_LIST'

export const EXHENTAI_API_TASK_PREFIX = 'EXHENTAI_TASK_'

export const QQ_MSG_TO_TG_PREFIX = 'QQ_MSG_'
export const TG_MSG_TO_QQ_PREFIX = 'TG_MSG_'
