export const EXHENTAI_DOWNLOADS = 'EXHENTAI_DOWNLOADS'

export const EXHENTAI_API_TASK_PREFIX = 'EXHENTAI_TASK_'

export const CMD_DEBOUNCE_PREFIX = 'CMD_DEBOUNCE:'

export const TWEET_INFO_CACHE_PREFIX = 'TWEET_INFO_CACHE:'
export const TWITTER_BIND_SESSION_PREFIX = 'TWITTER_BIND:'
export const TWITTER_TOKEN_PREFIX = 'TWITTER_TOKEN:'
